* oai
Emacs package, provide blocks ~#+begin_ai~ in Org mode for communication with LLMs APIs. Text oriented fork of org-ai.

Features:
- Tags: expansion of links in block
- Highlighting of code in markdown blocks
- Auto filling
- provide prompt engineering tools

* dependencies
- Optional: ~org-links~, available at MELA and at https://github.com/Anoncheg1/emacs-org-links

Tested for Emacs 30.2
* files
| File              | Purpose                                                        |
|-------------------+----------------------------------------------------------------|
| oai.el            | minor Org oai-mode and ~C-c C-c~ request activation command    |
| oai-restapi.el    | Connection to REST API (OpenAI-compatible)                     |
| oai-block.el      | handling ai block                                              |
| oai-block-tags.el | Handlings links in request window                              |
| oai-timers.el     | Notifications and handling waitings                            |
| oai-prompt.el     | Working with prompt-engineering, :chain parameter              |
| oai-async1.el     | Framework for handling callbacks of REST API requests (url.el) |
| oai-optional.el   | Hooks functions for postprocessing                             |

* Connection configuration
~oai-restapi-con-token~ - "token-string" or token per service: ~'(:openai "token-string1" :deepseek "token-string2")~ or nil for reading from "~/.authinfo" or "~/.authinfo.gpg"

~oai-restapi-con-service~ - 'openai or 'deepseek or use parameter at block like this: ~#+begin_ai :service openai~

* Supported services
- OpenAI
- Azure-OpenAI
- Perplexity.ai
- Anthropic
- DeepSeek
- Google
- Github
- Together

oai-restapi-con-service [[./oai-restapi.el]]
* Configuration
: git clone https://github.com/Anoncheg1/oai

#+begin_src elisp :results none :exports code :eval no
(add-to-list 'load-path "path/to/oai")
(require 'oai)
(add-hook 'org-mode-hook #'oai-mode) ; oai.el
(setq org-ai-api-creds-token "xxx") ; oai-restapi.el
#+end_src
** How to connect to not supported service?

#+begin_src elisp :results none :exports code :eval no
(plist-put oai-restapi-con-endpoints :local "http://localhost:8000/v1/chat/completions")
;; Optionally, set it as default
(setq oai-restapi-con-service 'local)
#+end_src

org-ai--openai-get-token-auth-source, org-ai--get-endpoint, org-ai--get-headers

Redefine:
- ~oai-restapi--get-headers~ - If you need some special HTTP headers.
- ~oai-restapi--get-single-response-text~ and ~oai-restapi--normalize-response~ - if HTTP responses is not standard for ~"stream":false~ and ~"stream":true~ respectively.

* Supported “[AI]:” in-text prefixes
- SYS-EVERYWHERE
- SYS - role: system
- AI - role: assistant
- AI_REASON - excluded
- ME - role: user

* Supported parameteres for #+begin_ai
- :model "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free" - string
- :service <service> - string symbol/string (oai-restapi-con-service)
- :max-tokens 150 - int
- :stream - bool
- :top-p float
- :temperature float
- :frequency-penalty float
- :presence-penalty float
- :sys-everywhere - string (sys-prompt-for-all-messages) [[./oai.el]]
- :chat :completion - bool (org-ai--request-type) [[./oai-block.el]]
- :chain - bool [[./oai-prompt.el]]
* debugging
To get full request body and more information set:
: (setopt oai-debug-buffer "*debug-oai*")
: (setq debug-on-error t) ; optional

Built-in url.el have ability to output request and resonse headers, for that you need to set
: (setq url-debug '(http))
* Extension guide
** How to add post-processing for text
There are a hook ~oai-restapi-after-chat-insertion-hook~ that accpet two arguments (par1 par2)
- type :: simbol \='role, \='text or'end,
- role-text :: text or role name,
- pos :: position before text insertion
- buffer :: target buffer with ai block for third position.

There is two implementations for hook in oai-optional.el:
- oai-optional-remove-distant-empty-lines-hook-function
-


Example to remove empty lines after AI answer:
#+begin_src elisp :results none :exports code :eval no
(require 'oai-optional) ; for `oai-optional-remove-distant-empty-lines'

(defun my/ai-postprocess (type _content _pos buf)
  (ignore _content _pos)
  (with-current-buffer buf
    (when (equal type 'end)
      (save-excursion
        (let* ((context (oai-block-p))
               (con-beg (org-element-property :contents-begin context))
               (con-end (org-element-property :contents-end context)))
          (oai-optional-remove-distant-empty-lines con-beg con-end))))))

(add-hook 'oai-restapi-after-chat-insertion-hook #'my/ai-postprocess)
#+end_src

* org-block functions
- org-in-src-block-p = oai-block-p
- oai-block-insert-result = oai-block-insert-result
- org-babel-where-is-src-block-result = oai-block-where-is-result
- org-fill-paragraph = oai-block-fill-paragraph
